name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/monafarms
            cd /var/repo/monafarms.git
            git fetch --all
            git --work-tree=/var/www/monafarms --git-dir=/var/repo/monafarms.git checkout -f main
            echo "Deployment completed at $(date)" > /var/www/monafarms/deployed.txt
