name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Starting deployment..."
            mkdir -p /var/www/monafarms
            cd /var/repo/monafarms.git || exit 1
            git fetch origin main
            git --work-tree=/var/www/monafarms --git-dir=/var/repo/monafarms.git checkout -f main
            echo "Deployment completed at $(date)" > /var/www/monafarms/deployed.txt
            echo "Files in /var/www/monafarms:"
            ls -la /var/www/monafarms
